# Use root/example as user/password credentials
version: '3.8'

services:

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 8090:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: patient-note-db
      ME_CONFIG_SITE_BASEURL: /
    networks:
      - patient-network
networks:
  patient-network:
    name: patient-network
    external: true