version: '3.8'
services:
  patient-ui-db:
    image: mysql:8.3.0
    container_name: patient-ui-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - patient-network

    environment:
      MYSQL_ROOT_PASSWORD: example
networks:
  patient-network:
    name: patient-network
    external: true